/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Final.compressed.glb 
Author: QuickDriftVR (https://sketchfab.com/QuickDriftVR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-2f54d1c5d3c943bfadc72ab656587c90
Title: Headphones
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/Final.compressed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.posterjpg.geometry}
        material={nodes.posterjpg.material}
        position={[0.61, 1.5, -0.17]}
        scale={0.479}
      />
      <mesh
        geometry={nodes.Poster2jpg.geometry}
        material={nodes.Poster2jpg.material}
        position={[-1.91, 1.35, 2.14]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.563, 1, 1]}
      />
      <mesh
        geometry={nodes.Poster1jpg.geometry}
        material={nodes.Poster1jpg.material}
        position={[-1.91, 1.53, 1.34]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.608}
      />
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Desk_1}
        position={[0.05, 0.989, 0.05]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.995, 0.994]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.Posters}
        position={[0.109, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.995, 0.994]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Keyboard}
        position={[0.02, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.995, 0.994]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.BG_Dark}
        position={[0.099, 0.353, 0.009]}
        rotation={[-1.553, 0, 0]}
        scale={[0.969, 0.989, 1.524]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Carpet}
        position={[0.109, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[1, 0.995, 0.994]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Emission}
        position={[0.139, 0.99, 0.01]}
        rotation={[-1.553, 0, 0]}
        scale={[1.048, 1.003, 0.994]}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Emission_Blue}
        position={[0.02, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.995, 0.994]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Trim_Sheet_Wall}
        position={[0.099, 0.99, -0.01]}
        rotation={[-1.553, 0, 0]}
        scale={[0.973, 0.979, 0.994]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.Monitor_Single}
        position={[0.02, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.973, 0.994]}
      />
      <mesh
        geometry={nodes["Cylinder001_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.173, 0.72, 0.422]}
        rotation={[-Math.PI / 2, 0, 2.688]}
        scale={0.003}
      />
      <mesh
        geometry={nodes["Cylinder002_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.173, 0.729, 0.422]}
        rotation={[-Math.PI / 2, 0, 2.688]}
        scale={[0.005, 0.005, 0.006]}
      />
      <mesh
        geometry={nodes["Cylinder003_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.173, 0.777, 0.422]}
        rotation={[-Math.PI / 2, 0, 2.688]}
        scale={[0.006, 0.006, 0.007]}
      />
      <mesh
        geometry={nodes["Box002_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.171, 0.928, 0.38]}
        rotation={[2.325, -0.952, 0.857]}
        scale={[0.003, 0.005, 0.005]}
      />
      <mesh
        geometry={nodes["Box003_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.215, 0.942, 0.401]}
        rotation={[2.325, -0.952, 0.857]}
        scale={[0.003, 0.005, 0.005]}
      />
      <mesh
        geometry={nodes["Box004_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-1.2, 1.123, 0.408]}
        rotation={[-2.13, -0.828, 2.437]}
        scale={[0.003, 0.005, 0.005]}
      />
      <mesh
        geometry={nodes["Box004_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.2, 1.123, 0.408]}
        rotation={[-2.13, -0.828, 2.437]}
        scale={[0.003, 0.005, 0.005]}
      />
      <mesh
        geometry={nodes["Spring001_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.158, 0.783, 0.395]}
        rotation={[-1.522, 0.465, 2.637]}
        scale={0.003}
      />
      <mesh
        geometry={nodes["Spring002_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.185, 0.783, 0.451]}
        rotation={[-1.22, 0.316, 2.67]}
        scale={0.003}
      />
      <mesh
        geometry={nodes["Spring003_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.171, 0.791, 0.422]}
        rotation={[-1.648, -0.157, 2.682]}
        scale={0.003}
      />
      <mesh
        geometry={nodes["Cylinder004_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.152, 0.879, 0.381]}
        rotation={[0, -0.454, Math.PI]}
        scale={0.005}
      />
      <mesh
        geometry={nodes["Cylinder005_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.184, 0.879, 0.446]}
        rotation={[0, -0.454, Math.PI]}
        scale={0.005}
      />
      <mesh
        geometry={nodes["Cylinder006_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-1.254, 1.033, 0.368]}
        rotation={[0, -0.454, Math.PI]}
        scale={[0.01, 0.01, 0.006]}
      />
      <group
        position={[-1.051, 1.14, 0.479]}
        rotation={[-1.869, -0.542, 2.605]}
        scale={0.005}
      >
        <mesh
          geometry={nodes.mesh_23.geometry}
          material={materials["07_-_Default"]}
        />
        <pointLight intensity={1} decay={2} />
      </group>
      <mesh
        geometry={nodes["Sphere001_09_-_Default_0"].geometry}
        material={materials["09_-_Default"]}
        position={[-1.051, 1.14, 0.479]}
        rotation={[-1.869, -0.542, 2.605]}
        scale={0.005}
      />
      <mesh
        geometry={nodes["Sphere002_03_-_Default_0"].geometry}
        material={materials["03_-_Default"]}
        position={[-0.933, 0.717, 0.363]}
        rotation={[-Math.PI / 2, 0, 2.688]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.Leg_LP4_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.655, 0.031, 1.165]}
        rotation={[3.086, -1.518, 3.084]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Leg_LP1_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.76, 0.031, 1.193]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Wheel_LP_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.059, 0.032, 1.408]}
        rotation={[0.008, -1.109, 0.007]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCylinder25_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.059, 0.032, 1.408]}
        rotation={[0.008, -1.109, 0.007]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.ChairBack_LP_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.76, 0.031, 1.193]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.ChairSeat_LP4_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.76, 0.031, 1.193]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCylinder26_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-1.184, 0.03, 1.108]}
        rotation={[-3.14, 0.1, 3.139]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Wheel_LP1_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-1.184, 0.03, 1.108]}
        rotation={[-3.14, 0.1, 3.139]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Leg_LP5_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.697, 0.031, 1.217]}
        rotation={[-3.141, -0.262, 3.138]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Underside_LP_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.76, 0.031, 1.193]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCube38_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.76, 0.031, 1.193]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Wheel_LP2_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.715, 0.031, 1.206]}
        rotation={[-3.14, -0.205, 3.139]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCylinder27_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.715, 0.031, 1.206]}
        rotation={[-3.14, -0.205, 3.139]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCube37_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.703, 0.651, 1.548]}
        rotation={[-3.135, 0.995, 3.136]}
        scale={[0.001, 0, 0.001]}
      />
      <mesh
        geometry={nodes.pCylinder28_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.759, 0.03, 1.493]}
        rotation={[0.037, -1.487, 0.036]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pCylinder29_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.458, 0.031, 1.739]}
        rotation={[0.039, -1.49, 0.037]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Wheel_LP3_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.759, 0.03, 1.493]}
        rotation={[0.037, -1.487, 0.036]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Leg_LP3_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.692, 0.031, 1.109]}
        rotation={[0.003, -0.367, 0.003]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Wheel_LP4_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.458, 0.031, 1.739]}
        rotation={[0.039, -1.49, 0.037]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Leg_LP2_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-0.756, 0.031, 1.126]}
        rotation={[-0.002, 0.89, 0.005]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/Final.compressed.glb");
