/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Final.glb 
Author: QuickDriftVR (https://sketchfab.com/QuickDriftVR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-2f54d1c5d3c943bfadc72ab656587c90
Title: Headphones
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props) {
  const { nodes, materials } = useGLTF("/models/Final.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.02, 0.99, 0]}
        rotation={[-1.553, 0, 0]}
        scale={[0.989, 0.995, 0.994]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Desk_1}
          position={[0.03, -0.05, 0]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Posters}
          position={[0.09, 0, 0]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Keyboard}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.BG_Dark}
          position={[0.08, -0.02, -0.64]}
          scale={[0.979, 0.994, 1.533]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Carpet}
          position={[0.09, 0, 0]}
          scale={[1.011, 1, 1]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Emission}
          position={[0.12, -0.01, 0]}
          scale={[1.059, 1.008, 1]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Emission_Blue}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Trim_Sheet_Wall}
          position={[0.08, 0.01, 0]}
          scale={[0.983, 0.984, 1]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Monitor_Single}
          scale={[1, 0.978, 1]}
        />
      </group>
      <group
        position={[-1.13, 0.7, 0.38]}
        rotation={[-Math.PI / 2, 0, 2.688]}
        scale={0.049}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.1}>
            <group
              position={[10.403, 86.338, -11.475]}
              rotation={[-Math.PI / 2, 0.96, 0]}
              scale={[0.576, 1, 1]}
            >
              <mesh
                geometry={nodes["Box004_07_-_Default_0"].geometry}
                material={materials["07_-_Default"]}
              />
              <mesh
                geometry={nodes["Box004_08_-_Default_0"].geometry}
                material={materials["08_-_Default"]}
              />
            </group>
            <group
              position={[-23.452, 89.893, -11.125]}
              rotation={[-Math.PI / 2, 0.611, 0]}
              scale={0.951}
            >
              <mesh
                geometry={nodes["Sphere001_09_-_Default_0"].geometry}
                material={materials["09_-_Default"]}
              />
              <mesh
                geometry={nodes.mesh_23.geometry}
                material={materials["07_-_Default"]}
              />
              <pointLight intensity={1} decay={2} />
            </group>
            <group
              position={[-15.871, 102.314, -11.408]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes["Sphere002_03_-_Default_0"].geometry}
                material={materials["03_-_Default"]}
                position={[-18.72, -32.1, -98.82]}
              />
            </group>
            <mesh
              geometry={nodes["Cylinder001_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
              position={[4.161, 4.055, -11.493]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.565}
            />
            <mesh
              geometry={nodes["Cylinder002_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
              position={[4.184, 5.988, -11.532]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1, 1.148]}
            />
            <mesh
              geometry={nodes["Cylinder003_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
              position={[4.184, 15.723, -11.532]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.281, 1.281, 1.47]}
            />
            <mesh
              geometry={nodes["Box002_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
              position={[7.457, 46.549, -3.623]}
              rotation={[Math.PI / 2, 1.134, Math.PI]}
              scale={[0.576, 1, 1]}
            />
            <mesh
              geometry={nodes["Box003_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
              position={[13.768, 49.379, -11.475]}
              rotation={[Math.PI / 2, 1.134, Math.PI]}
              scale={[0.576, 1, 1]}
            />
            <mesh
              geometry={nodes["Spring001_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[3.736, 16.963, -5.246]}
              rotation={[-1.396, -0.436, 0]}
              scale={0.607}
            />
            <mesh
              geometry={nodes["Spring002_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[3.736, 16.963, -17.879]}
              rotation={[-1.745, -0.436, 0]}
              scale={0.607}
            />
            <mesh
              geometry={nodes["Spring003_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[3.798, 18.507, -11.431]}
              rotation={[-Math.PI / 2, 0.175, 0]}
              scale={0.607}
            />
            <mesh
              geometry={nodes["Cylinder004_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[3.907, 36.459, -2.043]}
              rotation={[Math.PI, 0, 0]}
            />
            <mesh
              geometry={nodes["Cylinder005_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[3.907, 36.459, -16.95]}
              rotation={[Math.PI, 0, 0]}
            />
            <mesh
              geometry={nodes["Cylinder006_08_-_Default_0"].geometry}
              material={materials["08_-_Default"]}
              position={[23.714, 67.945, -8.935]}
              rotation={[Math.PI, 0, 0]}
              scale={[1.997, 1.997, 1.251]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.005, 0.06, 2.311]}
        rotation={[-1.569, -0.003, -2.461]}
        scale={0.967}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.12, -0.03, 1.39]}
            rotation={[Math.PI, -1.466, Math.PI]}
            scale={0.01}
          >
            <mesh
              geometry={nodes.Leg_LP4_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-3.462, 0, 10.655]}
              rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
            />
            <mesh
              geometry={nodes.Leg_LP1_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.Wheel_LP_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-58.139, 0, 48.659]}
              rotation={[-Math.PI, 0.114, -Math.PI]}
            />
            <mesh
              geometry={nodes.pCylinder25_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-58.139, 0, 48.659]}
              rotation={[-Math.PI, 0.114, -Math.PI]}
            />
            <mesh
              geometry={nodes.ChairBack_LP_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.ChairSeat_LP4_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.pCylinder26_lambert1_0.geometry}
              material={materials.lambert1}
              position={[31.27, 0, -31.948]}
              rotation={[0, 0.895, 0]}
            />
            <mesh
              geometry={nodes.Wheel_LP1_lambert1_0.geometry}
              material={materials.lambert1}
              position={[31.27, 0, -31.948]}
              rotation={[0, 0.895, 0]}
            />
            <mesh
              geometry={nodes.Leg_LP5_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-5.602, 0, 4.07]}
              rotation={[0, 1.257, 0]}
            />
            <mesh
              geometry={nodes.Underside_LP_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.pCube38_lambert1_0.geometry}
              material={materials.lambert1}
            />
            <mesh
              geometry={nodes.Wheel_LP2_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-3.632, 0, 3.211]}
              rotation={[0, 1.2, 0]}
            />
            <mesh
              geometry={nodes.pCylinder27_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-3.632, 0, 3.211]}
              rotation={[0, 1.2, 0]}
            />
            <mesh
              geometry={nodes.pCube37_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-33.983, 64.178, -14.779]}
              scale={[0.061, 0.036, 0.062]}
            />
            <mesh
              geometry={nodes.pCylinder28_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-26.088, 0, -16.813]}
              rotation={[-Math.PI, 0.492, -Math.PI]}
            />
            <mesh
              geometry={nodes.Wheel_LP3_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-26.088, 0, -16.813]}
              rotation={[-Math.PI, 0.492, -Math.PI]}
            />
            <mesh
              geometry={nodes.Leg_LP3_lambert1_0.geometry}
              material={materials.lambert1}
              position={[3.463, 0, 10.655]}
              rotation={[-Math.PI, -Math.PI / 5, -Math.PI]}
            />
            <mesh
              geometry={nodes.pCylinder29_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-64.369, 0, -4.511]}
              rotation={[-Math.PI, 0.495, -Math.PI]}
            />
            <mesh
              geometry={nodes.Wheel_LP4_lambert1_0.geometry}
              material={materials.lambert1}
              position={[-64.369, 0, -4.511]}
              rotation={[-Math.PI, 0.495, -Math.PI]}
            />
            <mesh
              geometry={nodes.Leg_LP2_lambert1_0.geometry}
              material={materials.lambert1}
              position={[5.602, 0, 4.07]}
              rotation={[0, -1.257, 0]}
            />
          </group>
        </group>
      </group>
      <mesh
        geometry={nodes.posterjpg.geometry}
        material={nodes.posterjpg.material}
        position={[0.61, 1.5, -0.17]}
        scale={0.479}
      />
      <mesh
        geometry={nodes.Poster2jpg.geometry}
        material={nodes.Poster2jpg.material}
        position={[-1.91, 1.35, 2.14]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.563, 1, 1]}
      />
      <mesh
        geometry={nodes.Poster1jpg.geometry}
        material={nodes.Poster1jpg.material}
        position={[-1.91, 1.53, 1.34]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.608}
      />
    </group>
  );
}

useGLTF.preload("/models/Final.glb");
